<a href="https://colab.research.google.com/github/rccrdmr/MAT422-Mathematics-for-DataScience/blob/main/1_2_Elements_of_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.2 Elements of Linear Algebra
_______________________________
###Topics:
* 1.2.1. Linear spaces
* 1.2.2. Orthogonality
* 1.2.3. Gram–Schmidt process
* 1.2.4. Eigenvalues and eigenvectors

In [1]:
import numpy as np

## 1.2.1. Linear Spaces


####1.2.1.1 Linear Combinations

**Definition (Linear Combination):**
A linear combination of vectors ${v_1},{v_2}, \dots,{v_n}$ is an expression of the form:

$$
{v} = \alpha_1{v_1} + \alpha_2{v_2} + \dots + \alpha_n{v_n}
$$

where $\alpha_1, \alpha_2, \dots, \alpha_n$ are scalars.


In [3]:
# Vectors
v1 = np.array([1, 2])
v2 = np.array([3, 4])

# Scalars
alpha1 = 2
alpha2 = 3

# Linear combination
v = alpha1 * v1 + alpha2 * v2

print(f"Linear combination v = {v}")

Linear combination v = [11 16]


**Definition (Linear Subspace):**  
A linear subspace of $V$ is a subset $U \subseteq V$ that is closed under vector addition and scalar multiplication. That is, for all $u_1, u_2 \in U$ and $\alpha \in \mathbb{R}$, it holds that:
$$
u_1 + u_2 \in U, \quad \text{and} \quad \alpha u_1 \in U
$$
In particular, $0$ is always in a linear subspace. A span of a set of vectors is a linear subspace.




**Definition (Span):**  
Let $w_1, \dots, w_m \in V$. The span of $\{w_1, \dots, w_m\}$, denoted $\text{span}(w_1, \dots, w_m)$, is the set of all linear combinations of the $w_j$'s. That is,
$$
\text{span}(w_1, \dots, w_m) = \left\{ \sum_{j=1}^{m} \alpha_j w_j : \alpha_1, \dots, \alpha_m \in \mathbb{R} \right\}
$$
A list of vectors that span a linear subspace $U$ is also referred to as a spanning set of $U$.

In [7]:
u1 = np.array([1, 2, 3])
u2 = np.array([4, 5, 6])
u3 = np.array([7, 8, 9])

U = np.array([u1, u2]).T

# Check if u3 is in the subspace spanned by u1 and u2
coeffs, residuals, rank, s = np.linalg.lstsq(U, u3, rcond=None)

if np.allclose(np.dot(U, coeffs), u3):
    print(f"u3 is in the subspace spanned by u1 and u2. Coefficients: {coeffs}")
else:
    print("u3 is not in the subspace spanned by u1 and u2.")

u3 is in the subspace spanned by u1 and u2. Coefficients: [-1.  2.]


**Lemma (Every Span is a Linear Subspace):**  
Let $W = \text{span}(w_1, \dots, w_m)$. Then $W$ is a linear subspace.

In [159]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
alpha1, alpha2 = 2, -1

v = alpha1 * v1 + alpha2 * v2
print(f"Linear Combination v = {v}")

u = np.array([5, 6, 7])

# Check if u is in the span (v1, v2)
try:
    coeffs = np.linalg.solve(np.array([v1, v2]).T, u)
    print(f"Vector u is in the span: u = {coeffs[0]}*v1 + {coeffs[1]}*v2")
except np.linalg.LinAlgError:
    print("Vector u is not in the span of v1 and v2")


Linear Combination v = [-2 -1  0]
Vector u is not in the span of v1 and v2


####1.2.1.2 Linear Independence and Dimension

**Definition (Linear Independence):**  
A list of vectors $u_1, \dots, u_m$ is **linearly independent** if none of them can be written as a linear combination of the others. Formally, this means:
$$
\forall i, \quad u_i \notin \text{span}(\{u_j : j \neq i\})
$$
If a list of vectors is not linearly independent, it is called **linearly dependent**.


In [22]:
u1 = np.array([1, 2, 3])
u2 = np.array([4, 5, 6])
u3 = np.array([7, 8, 9])

matrix = np.array([u1, u2, u3]).T

# Check for linear independence by calculating the rank
rank = np.linalg.matrix_rank(matrix)

if rank == matrix.shape[1]:
    print("The vectors are linearly independent.")
else:
    print("The vectors are linearly dependent.")

The vectors are linearly dependent.


**Lemma (Linear Independence Condition):**  
The vectors $u_1, \dots, u_m$ are linearly independent if and only if:
$$
\sum_{j=1}^{m} \alpha_j u_j = 0 \implies \alpha_j = 0, \forall j
$$
Equivalently, $u_1, \dots, u_m$ are linearly dependent if and only if there exist $\alpha_j$'s, not all zero, such that:
$$
\sum_{j=1}^{m} \alpha_j u_j = 0
$$

In [16]:
u1 = np.array([1, 0, 0])
u2 = np.array([0, 1, 0])
u3 = np.array([0, 0, 1])

matrix = np.array([u1, u2, u3]).T

# Solve the equation α1*u1 + α2*u2 + α3*u3 = 0
coeffs, residuals, rank, s = np.linalg.lstsq(matrix, np.zeros(len(u1)), rcond=None)

if np.allclose(coeffs, 0):
    print("The only solution is the trivial one: α1 = α2 = α3 = 0. The vectors are linearly independent.")
else:
    print("There exists a non-trivial solution. The vectors are linearly dependent.")


The only solution is the trivial one: α1 = α2 = α3 = 0. The vectors are linearly independent.


**Definition (Basis of a Space):**  
Let $U$ be a linear subspace of $V$. A basis of $U$ is a list of vectors $u_1, \dots, u_m$ in $U$ that:
1. Span $U$, that is, $U = \text{span}(u_1, \dots, u_m)$; and
2. Are linearly independent.

In [17]:
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
v3 = np.array([0, 0, 1])

matrix = np.array([v1, v2, v3])

# Calculate the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

# Check if they form a basis
if rank == 3:
    print(f"The vectors form a basis for R^3 and span a space of dimension {rank}.")
else:
    print(f"The vectors do not form a basis. They span a space of dimension {rank}.")

The vectors form a basis for R^3 and span a space of dimension 3.


**Theorem (Dimension Theorem):**  
Let $U$ be a linear subspace of $V$. Any basis of $U$ always has the same number of elements. All bases of $U$ have the same length, that is, the same number of elements. We call this number the dimension of $U$ and denote it $\text{dim}(U)$.


In [18]:
# Define two sets of basis vectors for a subspace of R^3
basis1 = np.array([[1, 0, 0], [0, 1, 0]])  # Set 1
basis2 = np.array([[1, 1, 0], [-1, 1, 0]]) # Set 2

# Calculate the ranks
rank1 = np.linalg.matrix_rank(basis1)
rank2 = np.linalg.matrix_rank(basis2)

if rank1 == rank2:
    print(f"Both sets form a basis for a subspace of dimension {rank1}.")
else:
    print("The bases do not span the same dimension.")


Both sets form a basis for a subspace of dimension 2.


**Lemma (Characterization of Linearly Dependent Sets):**  
Let $u_1, \dots, u_m$ be a linearly dependent list of vectors with a linearly independent subset $u_i$, $i \in \{1, \dots, k\}, k < m$. Then there is an $i > k$ such that:
1. $u_i \in \text{span}(u_1, \dots, u_{i-1})$
2. $\text{span}(\{u_j : j \in \{1, \dots, m\}\}) = \text{span}(\{u_j : j \in \{1, \dots, m\}, j \neq i\})$


In [20]:
u1 = np.array([1, 2, 3])
u2 = np.array([2, 4, 6])
u3 = np.array([3, 6, 9])

# Check if any vector can be expressed as a linear combination of the others
matrix = np.array([u1, u2]).T
coeffs, residuals, rank, s = np.linalg.lstsq(matrix, u3, rcond=None)

if np.allclose(np.dot(matrix, coeffs), u3):
    print(f"Vector u3 can be written as a linear combination: u3 = {coeffs[0]}*u1 + {coeffs[1]}*u2")
else:
    print("No vector can be expressed as a linear combination of the others.")

Vector u3 can be written as a linear combination: u3 = 0.5999999999999998*u1 + 1.2000000000000002*u2


## 1.2.2. Orthogonality


#### 1.2.2.1 Orthonormal Bases

**Definition (Norm and Inner Product):**  
The **inner product** of two vectors $u, v \in \mathbb{R}^n$ is defined as:
$$
\langle u, v \rangle = u \cdot v = \sum_{i=1}^{n} u_i v_i
$$
The **norm** of a vector $u$ is defined as:
$$\|u\| = \sqrt{\sum_{i=1}^{n} u_i^2}$$

In [23]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

# Calculate the inner product ⟨u, v⟩
inner_product = np.dot(u, v)

# Calculate the norm ‖u‖
norm_u = np.linalg.norm(u)

print(f"Inner product ⟨u, v⟩ = {inner_product}")
print(f"Norm ‖u‖ = {norm_u}")

Inner product ⟨u, v⟩ = 32
Norm ‖u‖ = 3.7416573867739413


**Definition (Orthonormal Bases):**  
A list of vectors $\{u_1, \dots, u_m\}$ is **orthonormal** if the $u_i$’s are pairwise orthogonal and each has norm 1. That is, for all $i$ and all $j \neq i$:
$$
\langle u_i, u_j \rangle = 0, \quad \text{and} \quad \|u_i\| = 1
$$

In [26]:
u1 = np.array([1, 0, 0])
u2 = np.array([0, 1, 0])
u3 = np.array([0, 0, 1])

def is_orthonormal(vectors):
    for i in range(len(vectors)):
        for j in range(len(vectors)):
            inner_product = np.dot(vectors[i], vectors[j])
            if i == j and not np.isclose(inner_product, 1):
                return False
            elif i != j and not np.isclose(inner_product, 0):
                return False
    return True

# Check if {u1, u2, u3} is orthonormal
vectors = [u1, u2, u3]
if is_orthonormal(vectors):
    print("The vectors are orthonormal.")
else:
    print("The vectors are not orthonormal.")

The vectors are orthonormal.


**Lemma:**  
Let $\{u_1, \dots, u_m\}$ be an orthonormal list of vectors.

1. The norm of any linear combination of these vectors satisfies:
$$
\left\|\sum_{j=1}^{m} \alpha_j u_j \right\|^2 = \sum_{j=1}^{m} \alpha_j^2
$$
2. The vectors $\{u_1, \dots, u_m\}$ are linearly independent.


####1.2.2.2 Best Approximation Theorem


**Theorem (Best Approximation Theorem):**  
Let $U \subseteq V$ be a linear subspace with an orthonormal basis $q_1, \dots, q_m$ and let $v \in V$. For any $u \in U$:
$$
\|v - P_U v\| \leq \|v - u\|
$$
Furthermore, if $u \in U$ and the inequality above is an equality, then $u = P_U v$.




In [47]:
# Define the orthonormal basis for subspace U
q1 = np.array([1, 0])
q2 = np.array([0, 1])

v = np.array([3, 4])
u = np.array([1, 2])

# orthogonal projection P_U v
PU_v = np.dot(v, q1) * q1 + np.dot(v, q2) * q2

if np.linalg.norm(v - PU_v) <= np.linalg.norm(v - u):
    print("The Best Approximation Theorem is satisfied.")
else:
    print("The Best Approximation Theorem is not satisfied.")

The Best Approximation Theorem is satisfied.


**Definition (Orthogonal Projection):**  
Let $U \subseteq V$ be a linear subspace with an orthonormal basis $q_1, \dots, q_m$. The orthogonal projection of $v \in V$ on $U$ is defined as:
$$
P_U v = \sum_{j=1}^{m} \langle v, q_j \rangle q_j
$$


In [29]:
q1 = np.array([1, 0])
q2 = np.array([0, 1])

v = np.array([3, 4])

PU_v = np.dot(v, q1) * q1 + np.dot(v, q2) * q2

print(f"Orthogonal projection P_U v = {PU_v}")

Orthogonal projection P_U v = [3 4]


**Lemma (Pythagorean Theorem):**  
Let $u, v \in V$ be orthogonal. Then:
$$
\|u + v\|^2 = \|u\|^2 + \|v\|^2
$$

**Lemma (Cauchy-Schwarz Inequality):**  
For any $u, v \in V$:
$$
|\langle u, v \rangle| \leq \|u\| \|v\|
$$

**Lemma (Orthogonal Decomposition):**  
Let $U \subseteq V$ be a linear subspace with an orthonormal basis $q_1, \dots, q_m$ and let $v \in V$. For any $u \in U$:
$$
\langle v - P_U v, u \rangle = 0
$$
In particular, $v$ can be decomposed as $(v - P_U v) + P_U v$, where the two terms are orthogonal.


In [37]:
q1 = np.array([1, 0])
q2 = np.array([0, 1])

v = np.array([3, 4])

PU_v = np.dot(v, q1) * q1 + np.dot(v, q2) * q2

orthogonal_complement = v - PU_v

# Verify that ⟨v - P_U v, u⟩ = 0 for all u in U
for q in [q1, q2]:
    if np.isclose(np.dot(orthogonal_complement, q), 0):
        print(f"The vector {orthogonal_complement} is orthogonal to {q}.")
    else:
        print(f"The vector {orthogonal_complement} is not orthogonal to {q}.")

The vector [0 0] is orthogonal to [1 0].
The vector [0 0] is orthogonal to [0 1].


## 1.2.3 Gram-Schmidt Process


**Theorem (Gram-Schmidt Process):**  
Let $a_1, \dots, a_m $ in $\mathbb{R}^n$ be linearly independent. Then there exists an orthonormal basis $q_1, \dots, q_m$ of the span $ \text{span}(a_1, \dots, a_m)$.

The orthonormal basis is constructed as follows:
$$
q_1 = \frac{a_1}{\|a_1\|}, \quad
q_i = \frac{a_i - \sum_{j=1}^{i-1} \langle a_i, q_j \rangle q_j}{\|a_i - \sum_{j=1}^{i-1} \langle a_i, q_j \rangle q_j\|} \text{ for } i = 2, \dots, m.
$$

In [42]:
def gram_schmidt(A):
    """Applies the Gram-Schmidt process to the columns of matrix A."""
    Q = np.zeros_like(A)  # Q with same shape as A

    for i in range(A.shape[1]):
        q_i = A[:, i]  # Start with current vector a_i

        for j in range(i):
            q_i -= np.dot(A[:, i], Q[:, j]) * Q[:, j]  # Subtract projections onto previously computed q_j

        Q[:, i] = q_i / np.linalg.norm(q_i)  # Normalize q_i to get the orthonormal vector

    return Q

# Example:
a1 = np.array([1.0, 1.0, 0.0])
a2 = np.array([1.0, 0.0, 1.0])
a3 = np.array([0.0, 1.0, 1.0])
A = np.column_stack([a1, a2, a3])

Q = gram_schmidt(A)

print("Orthonormal basis Q:")
print(Q)

Orthonormal basis Q:
[[ 0.70710678  0.40824829 -0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.          0.81649658  0.57735027]]


## 1.2.4 Eigenvalues and Eigenvectors

**Definition (Eigenvalues and Eigenvectors):**  
Let $A \in \mathbb{R}^{d \times d}$ be a square matrix. Then $\lambda \in \mathbb{R}$ is an eigenvalue of $A$ if there exists a nonzero vector $x \neq 0$ such that

$$
A x = \lambda x.
$$

The vector $x$ is referred to as an eigenvector.

**Lemma (Number of Eigenvalues):**  
Let $ A \in \mathbb{R}^{d \times d} $ and let $ \lambda_1, \dots, \lambda_m $ be distinct eigenvalues of $ A $ with corresponding nonzero eigenvectors $ x_1, \dots, x_m $. Then $ x_1, \dots, x_m $ are linearly independent. As a result, $ m \leq d $.


In [46]:
A = np.array([[4, 1],
              [2, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:")
print(eigenvectors)

# Check if eigenvectors are linearly independent
rank = np.linalg.matrix_rank(eigenvectors)

if rank == eigenvectors.shape[1]:
    print("The eigenvectors are linearly independent.")
else:
    print("The eigenvectors are not linearly independent.")

Eigenvalues of A: [5. 2.]
Eigenvectors of A:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]
The eigenvectors are linearly independent.


####1.2.4.1 Diagonalization of Symmetric Matrices

**Definition:**
\
A symmetric matrix $A$ is **diagonalizable**, meaning it can be written in the form:

$$
A = PDP^{-1}
$$

where $P$ is an orthogonal matrix (i.e., $P^{-1} = P^T$), and $D$ is a diagonal matrix containing the eigenvalues of $A$. Symmetric matrices have real eigenvalues, and their eigenvectors are orthogonal.

In [48]:
# Symmetric matrix
A = np.array([[4, 1, 1],
              [1, 4, 1],
              [1, 1, 4]])

eigenvalues, eigenvectors = np.linalg.eigh(A)

# eigenvalues -> diagonal matrix D
D = np.diag(eigenvalues)

# eigenvectors -> matrix P
P = eigenvectors

# Check if A = PDP^T
A_reconstructed = P @ D @ P.T

print("Original matrix A:")
print(A)
print("Reconstructed matrix A from PDP^T:")
print(A_reconstructed)

if np.allclose(A, A_reconstructed):
    print("The matrix A is diagonalizable as A = PDP^T.")
else:
    print("The matrix A is not diagonalizable in the form A = PDP^T.")

Original matrix A:
[[4 1 1]
 [1 4 1]
 [1 1 4]]
Reconstructed matrix A from PDP^T:
[[4. 1. 1.]
 [1. 4. 1.]
 [1. 1. 4.]]
The matrix A is diagonalizable as A = PDP^T.


**Theorem (Diagonalization of Symmetric Matrices):**  
If $ A $ is symmetric, then any two eigenvectors from different eigenspaces are orthogonal.


**Theorem (The Spectral Theorem for Symmetric Matrices):**  
An $ n \times n $ symmetric matrix $ A $ has the following properties:
- $ A $ has $ n $ real eigenvalues, counting multiplicities.
- If $ \lambda $ is an eigenvalue of $ A $ with multiplicity $ k $, then the eigenspace for $ \lambda $ is $ k $-dimensional.
- The eigenspaces are mutually orthogonal, in the sense that eigenvectors corresponding to different eigenvalues are orthogonal.
- $ A $ is orthogonally diagonalizable.

####1.2.4.2 Constrained Optimization

**Theorem (Constrained Optimization):**  
Let $ A $ be an $ n \times n $ symmetric matrix with an orthogonal diagonalization $ A = P D P^{-1} $. The columns of $ P $ are orthonormal eigenvectors $ v_1, \dots, v_n $ of $ A $. Assume that the diagonal of $ D $ is arranged so that $ \lambda_1 \leq \lambda_2 \leq \dots \leq \lambda_n $. Then:

$$
\min_{x \neq 0} \frac{x^T A x}{x^T x} = \lambda_1
$$

is achieved when $ x = v_1 $, and

$$
\max_{x \neq 0} \frac{x^T A x}{x^T x} = \lambda_n
$$

is achieved when $ x = v_n $.
